installed_at: '2026-03-15T19:22:55+00:00'
skill_id: git/mastering-typescript
git_repo: https://github.com/SpillwaveSolutions/mastering-typescript-skill
skill_path: /private/var/folders/q5/k0v3d0552jj8mpn5l2g5_ys80000gp/T/skilz-git-y5tduz_f/mastering-typescript
git_sha: 2f74a00f731f2ea4d48f45d852067a7be8efd0d1
skilz_version: 1.10.0
install_mode: copy
canonical_path: null
